// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBq8EC-M7u7JpAyeZDidx18YaYU-93ayM',
    appId: '1:18177252443:web:bcdca400f9438d1c33f37e',
    messagingSenderId: '18177252443',
    projectId: 'fir-flutter-d45f6',
    authDomain: 'fir-flutter-d45f6.firebaseapp.com',
    databaseURL: 'https://fir-flutter-d45f6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-d45f6.appspot.com',
    measurementId: 'G-7ZBVC2248G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZWRMD88U1An4eGbxKQ3gAV0lc4fy6hsI',
    appId: '1:18177252443:android:e295018828500fe833f37e',
    messagingSenderId: '18177252443',
    projectId: 'fir-flutter-d45f6',
    databaseURL: 'https://fir-flutter-d45f6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-d45f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81urMOGXYtuCTbsLwUE-v11jfsV151iM',
    appId: '1:18177252443:ios:7b838790be8dfa5133f37e',
    messagingSenderId: '18177252443',
    projectId: 'fir-flutter-d45f6',
    databaseURL: 'https://fir-flutter-d45f6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-d45f6.appspot.com',
    iosClientId: '18177252443-5cn19k2dfc81qjkgudnbg3kch7hqbmcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81urMOGXYtuCTbsLwUE-v11jfsV151iM',
    appId: '1:18177252443:ios:a861f4ab7c6c7afd33f37e',
    messagingSenderId: '18177252443',
    projectId: 'fir-flutter-d45f6',
    databaseURL: 'https://fir-flutter-d45f6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-d45f6.appspot.com',
    iosClientId: '18177252443-6hr2mq5gqgdtnuii16b66ka5vf8i7tsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
